version: '3.3'

services:
  priceservice:
    container_name: price_service
    build: .
    image: price_service

    ports:
      - "4004:4004"

    networks:
      - default
      - messagebrokerservice_default

        
networks:
  default:
    internal: true
  messagebrokerservice_default:
    external: true